//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public avion()
        {
            this.vols = new HashSet<vol>();
        }
    
        public int num_av { get; set; }
        public string modele_av { get; set; }
        public Nullable<int> capacite_av { get; set; }
        public Nullable<int> nbr_h_travail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vol> vols { get; set; }
    }
}
