//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class billet
    {
        public int num_place { get; set; }
        public string classe_siege { get; set; }
        public Nullable<int> num_resa { get; set; }
        public string num_passport_psg { get; set; }
    
        public virtual passager passager { get; set; }
        public virtual reservation reservation { get; set; }
    }
}
