//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class passager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public passager()
        {
            this.billets = new HashSet<billet>();
        }
    
        public string num_passport { get; set; }
        public string nom_psg { get; set; }
        public string prenom_psg { get; set; }
        public string tel_psg { get; set; }
        public Nullable<System.DateTime> date_naiss_psg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billet> billets { get; set; }
    }
}
