//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservation()
        {
            this.billets = new HashSet<billet>();
        }
    
        public int num_resa { get; set; }
        public Nullable<System.DateTime> date_resa { get; set; }
        public Nullable<int> num_cl { get; set; }
        public Nullable<int> num_user { get; set; }
        public Nullable<int> num_v { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billet> billets { get; set; }
        public virtual client client { get; set; }
        public virtual utilisateur utilisateur { get; set; }
        public virtual vol vol { get; set; }
    }
}
