//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class vol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vol()
        {
            this.reservations = new HashSet<reservation>();
            this.lignes = new HashSet<ligne>();
        }
    
        public int num_v { get; set; }
        public Nullable<int> aeroport_d { get; set; }
        public Nullable<int> aeroport_a { get; set; }
        public Nullable<int> num_pil { get; set; }
        public Nullable<int> num_av { get; set; }
        public Nullable<System.DateTime> date_d { get; set; }
        public Nullable<System.DateTime> date_a { get; set; }
    
        public virtual aeroport aeroport { get; set; }
        public virtual aeroport aeroport1 { get; set; }
        public virtual avion avion { get; set; }
        public virtual pilote pilote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ligne> lignes { get; set; }
    }
}
